# ID Badge maker
print("Welcome to the ID Badge maker 1.0")
print("Please Enter the Following")
f_name = input("First Name: ")
l_name = input("Last Name: ")
email = input("Email Address: ")
p_num = input("Phone Number: ")
job = input("Job Title: ")
idn = input("ID Number: ")
h_color = input("Hair Color: ")
e_color = input("Eye Color: ")
mon = input("Month you started work at Bucks Youth Ubiquity: ")
training = input("Did you recieve a clown certificate?: ")
print()
print()
#Output of the Badge starts here
print("Here's your new ID Badge")
print("*"*40)
print(f"{f_name.upper()},{l_name.title()}")
print(job.title())
print(f'ID: {idn}')
print()
print(email.lower())
print(p_num)
print()
print(f'Hair: {h_color.upper():15} Eyes: {e_color.upper()}')
print(f'Month: {mon.upper():14} Training: {training.upper()}')
print("*"*40)
#output of badge ends here