# Mad Lib Project

print("Welcome to POGGERS Mad Lib 0.0.1")
print("- Where you make the store before you know! -")
print("*"*50)
print("Please enter the following")
actor = input("An actor/actress: ")
object = input("An object: ")
adj = input("An adjective: ")
song = input("Your favorite song: ")
vec = input("A land based vehicle: ")
col = input("Favorite color: ")
ani = input("Cutest animal you know: ")
food = input("Your favorite food:")
rew = input("Something from last year's christmas wishlist: ")
print("Okay, here we go!")
print("*"*50)
print(f"So the other day I was on my porch in LA when all of a sudden {actor} comes running down the street.")
print(f"I saw that {actor} was holding a {object} that was a little more than they could handle.")
print(f"I was thinking to myself that this was the {adj}est thing I ever saw. Next thing I know")
print(f"I'm hearing {song} in the distance. {actor} starts to panic and yell for help, when all of a sudden")
print(f"a fleet of {vec}s being driven by {ani}s with that {song} playing on there radios. {actor} is still")
print(f"yelling for help when we lock eyes. I knew I shouldn't have worn my favrite {col} shirt cause")
print(f"{actor} started running at me when the {ani} start throwing feces and it got all over the two of us.")
print(f"I open my door for {actor} and they thank me, and ask me to hide them for bit. I asked why should I?")
print(f"{actor} said they had a {rew} or {food}. I said both will do. {actor} was relunctant to give, but is")
print(f"now safe in my basement. Anyways, now I have {ani} searching the streets at my house. but atleaast they")
print(f"play {song} all the time now.")
print("THE END")
print("*"*50)
